version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/sifter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/yomi-api"
    schedule:
      interval: "weekly"
