services:
  strfry_shiritori:
    build: ./sifter
    container_name: strfry_shiritori
    command: --config=config/strfry.conf relay
    volumes:
      - ./config:/app/config
      - ./resource:/app/resource
      - ./strfry-db:/app/strfry-db
    environment:
      - RESOURCE_DIR
      - YOMI_API_BASE_URL
    pid: host
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "20"

  caddy_shiritori_relay:
    image: caddy:2.7.5
    container_name: caddy_shiritori_relay
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./web:/srv
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  caddy_data:
  caddy_config:
